blabber/urls.py
from django.urls import path

from . import views

app_name = 'blabber'

urlpatterns = [
    path('home/', views.HomeView.as_view(), name='home'),
    path('<slug:username>/', views.ProfileView.as_view(), name='profile'),
    path('avatar/change/<int:pk>/', views.AvatarView.as_view(), name='avatar'),
    path('posts/<int:pk>/like/', views.LikeToggleView.as_view(), name='like_toggle'),
    path('posts/add_post/', views.PostFormView.as_view(), name='add_post'),
    path('posts/<int:pk>/comment/', views.CommentFormView.as_view(), name='comment'),
]

social_network/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blabber.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blabber/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.utils.text import Truncator


class User(AbstractUser):
    """Custom user model"""
    GENDER_CHOICES = {
        ('M', 'Male'),
        ('F', 'Female'),
    }

    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    friends = models.ManyToManyField('self', blank=True)

    def get_avatar_url(self):
        if self.avatar:
            return self.avatar.url
        return ''


class Post(models.Model):
    text = models.TextField()
    photo = models.ImageField(upload_to='photos/', null=True, blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='posts')
    date_posted = models.DateTimeField(auto_now_add=True)  # Date and time set at object creation
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)

    class Meta:
        ordering = ['-date_posted']

    def __str__(self):
        truncated_text = Truncator(self.text)
        return truncated_text.chars(50)


class Comment(models.Model):
    text = models.TextField()
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comments')
    to = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    date_commented = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)

    def __str__(self):
        truncated_text = Truncator(self.text)
        return truncated_text.chars(50)


class Message(models.Model):
    body = models.CharField(max_length=1000)
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='messages_sent')
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='messages_received')
    date_delivered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        truncated_body = Truncator(self.body)
        return truncated_body.chars(50)

blabber/forms.py
from django import forms

from .models import Comment, Post, User


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['text', 'photo']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 4})
        }


class AvatarForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['avatar']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 2})
        }

blabber/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, resolve
from django.views import generic

from .forms import AvatarForm, CommentForm, PostForm
from .models import Post, User


class HomeView(generic.ListView):
    model = Post
    template_name = 'blabber/home.html'
    context_object_name = 'posts'

    def get_context_data(self, object_list=None, **kwargs):
        """Insert the forms into the context dict."""
        context = super().get_context_data(**kwargs)
        if 'post_form' not in context:
            context['post_form'] = PostForm()
        if 'comment_form' not in context:
            context['comment_form'] = CommentForm()
        return context


class ProfileView(generic.DetailView):
    model = User
    template_name = 'blabber/profile.html'
    context_object_name = 'custom_user'
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        """Insert the forms into the context dict."""
        context = super().get_context_data(**kwargs)
        if 'post_form' not in context:
            context['post_form'] = PostForm()
        if 'comment_form' not in context:
            context['comment_form'] = CommentForm()
        return context

    # def get(self, request, *args, **kwargs):
    #     self.object = self.get_object()
    #     form = PostForm()
    #     context = self.get_context_data()
    #     context.update({'form': form})
    #     return self.render_to_response(context)

    # def post(self, request):
    #     form = PostForm(request.POST, request.FILES)
    #     user = request.user
    #     if form.is_valid():
    #         post = form.save(commit=False)
    #         post.created_by = user
    #         post.save()
    #         return redirect('blabber:home')


class CommentFormView(generic.FormView):
    form_class = CommentForm

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            pk = kwargs['pk']
            return self.form_valid(form, pk)
        else:
            return self.form_invalid(form)

    def form_valid(self, form, pk):
        comment = form.save(commit=False)
        comment.created_by = self.request.user
        comment.to = Post.objects.get(pk=pk)
        comment.save()
        return redirect(self.request.POST.get('next'))


class PostFormView(generic.FormView):
    form_class = PostForm

    def form_valid(self, form):
        post = form.save(commit=False)
        post.created_by = self.request.user
        post.save()
        return redirect(self.request.POST.get('next'))


class AvatarView(generic.UpdateView):
    model = User
    form_class = AvatarForm
    template_name = 'blabber/edit_avatar.html'

    def get_success_url(self):
        user = self.get_object()
        url = reverse('blabber:profile', args=[user.username])
        return url


class LikeToggleView(generic.View):

    def get(self, request, pk=None):
        post = get_object_or_404(Post, pk=pk)
        user = request.user
        url = request.GET.get('next')
        if user.is_authenticated:
            if post.likes.filter(pk=user.pk).exists():
                post.likes.remove(user)
            else:
                post.likes.add(user)
            post.save()
        if request.is_ajax():
            data = {
                'likes_count': post.likes.count()
            }
            return JsonResponse(data)
        return HttpResponseRedirect(url)

blabber/templates/blabber/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en-US">
<head>
	<meta charset="utf-8">
	<title>{% block title %}Blabber{% endblock %}</title>
	<link rel="stylesheet" href="{% static 'blabber/css/base.css' %}">
	{% block css %}{% endblock %}
</head>
<body>
	<nav class="nav">
		<h1 class="brand">
			<a href="{% url 'blabber:home' %}">Blabber</a>
		</h1>
		<input for="btn-search" type="text" name="search" placeholder="Search blabber">
		<button id="btn-search">Search</button>
		{% if user.is_authenticated %}
			<a href="#">Logout</a>
		{% else %}
			<a href="#">Sign up</a>
			<a href="#">Login</a>
		{% endif %}

		<ul class="navbar">
			<li><a href="{% url 'blabber:home' %}">Home</a></li>
			<li><a href="{% url 'blabber:profile' user.username %}">Profile</a></li>
			<li><a href="#">Messages</a></li>
			<li><a href="#">Notifications</a></li>
		</ul>
	</nav>

	{% block content %}{% endblock %}

	<!-- 	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
 -->
	{% block script %}
		<script>
			function showComments(event) {
				event.preventDefault()
				var totalComments = this.getAttribute('data-total-comments')

				if (parseInt(totalComments) > 0) {
					var commentBox = this.parentElement.nextElementSibling
					var comments = commentBox.getElementsByClassName('comments')[0]

					if (comments.hasAttribute('hidden')) {
						comments.removeAttribute('hidden')
					}
				}
			}

			var comments = document.getElementsByClassName('collapse')

			var i
			for (i = 0; i < comments.length; i++) {
				comments[i].addEventListener('click', showComments)
			}

		</script>
	{% endblock %}
</body>
</html>

blabber/templates/blabber/edit_avatar.html
{% extends 'blabber/base.html' %}

{% block title %}Choose a photo{% endblock %}

{% block content %}
	<div>
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Submit</button>
		</form>
	</div>
{% endblock %}

blabber/templates/blabber/home.html
{% extends 'blabber/base.html' %}

{% block title %}Blabber{% endblock %}

{% block content %}

	{% include 'blabber/includes/post_form.html' %}

	{% include 'blabber/includes/post_list.html' %}
{% endblock %}

blabber/templates/blabber/includes/post_form.html
<div id="post-form">
	<form method="post" enctype="multipart/form-data" action="{% url 'blabber:add_post' %}">
		{% csrf_token %}
		<input type="hidden" name="next" value="{{ request.path }}">
		<table>
			<tbody>
				<tr>
					<td class="width-10">
						<div class="container-avatar" style="width: 50px; height: 50px">
							<img src="{{ user.get_avatar_url }}" alt="{{ user.get_full_name }}">
						</div>
					</td>
					<td class="width-80">
						{% for field in post_form %}
							{{ field }}
						{% endfor %}
					</td>
					<td class="width-10">
						<button type="submit">Post</button>
					</td>
				</tr>
			</tbody>
		</table>
	</form>
</div>

blabber/templates/blabber/includes/post_list.html
{% if posts.exists %}
	{% for post in posts %}
		<div class="container">
			<a href="{% url 'blabber:profile' post.created_by.username %}"><h3>{{ post.created_by.get_full_name }}</h3></a>

			<p>{{ post.text }}</p>

			{% if post.photo %}
				<div class="container-photo">
					<img src="{{ post.photo.url }}">
				</div>
			{% endif %}

			<p><small>{{ post.date_posted|timesince }}</small></p>
			<div>
				<a href="{% url 'blabber:like_toggle' post.pk %}?next={{ request.path|urlencode }}">{{ post.likes.count }} Like</a>
				<a href="#" class="collapse" data-total-comments="{{ post.comments.count }}">{{ post.comments.count }} Comment</a>
			</div>

			<div class="comment-box">
				<div class="comments" hidden>
					{% if post.comments.exists %}
						{% for comment in post.comments.all %}
							<div class="comment">
								<a href="{% url 'blabber:profile' comment.created_by.username %}">{{ comment.created_by.get_full_name }}</a>

								<p>{{ comment.text }}</p>

								<p><small>{{ comment.date_commented|timesince }}</small></p>
							</div>
						{% endfor %}
					{% endif %}
				</div>

				<form method="post" action="{% url 'blabber:comment' post.pk %}">
					{% csrf_token %}
					<input type="hidden" name="next" value="{{ request.path }}">
					<div style="float: left; width: 80%;">
						{% for field in comment_form %}
							{{ field }}
						{% endfor %}
					</div>
						<button>Comment</button>
					</div>
				</form>
			</div>
		</div>
	{% endfor %}
{% else %}
	<p>No post available</p>
{% endif %}

blabber/templates/blabber/profile.html
{% extends 'blabber/base.html' %}

{% block title %}{{ custom_user.get_full_name }}{% endblock %}

{% block content %}
	<div class="container-header">
		<div class="container-avatar center">
			<img src="{{ custom_user.get_avatar_url }}" alt="Display photo">
		</div>
		<div class="center-text">
			{% if custom_user == user %}
				<a href="{% url 'blabber:avatar' custom_user.pk %}">Edit photo</a>
			{% endif %}
			<h2>{{ custom_user.get_full_name }}</h2>
		</div>
	</div>

	{% if custom_user == user %}
		{% include 'blabber/includes/post_form.html' %}
	{% endif %}

	{% include 'blabber/includes/post_list.html' with posts=custom_user.posts.all %}
{% endblock %}